export const mySocials = [
  {
    name: "Github",
    href: "https://github.com/Hell086",
    icon: "/assets/socials/github.svg",
  },
  {
    name: "Linkedin",
    href: "https://www.linkedin.com/in/binay-shrestha-bbbbb52a5/",
    icon: "/assets/socials/linkedin.svg",
  },
  {
    name: "Instagram",
    href: "https://www.instagram.com/binayx_art/",
    icon: "/assets/socials/instagram.svg",
  },
];

export const experiences = [
   {
    worked: "Freelance",
    job: "Artist",
    date: "2018-Present",
    contents: [
      "I began my professional artistic journey in 2018, focusing on commission-based artworks that allowed me to connect directly with collectors and art enthusiasts. Over time, I expanded my practice, creating not only personal work but also mural artworks that brought spaces to life with colors, form, and storytelling. Each piece I created was a step in refining my style and understanding what resonates with people.",
      "Along the way, I collaborated with fellow artists on various projects, exchanging ideas and pushing creative boundaries. Through selling my art and completing commissions, I was able to turn my passion into a sustainable career while building a supportive community that follows and values my artistic growth. This journey has been a blend of exploration, collaboration, and dedication, shaping me into the professional artist I am today.",
    ],
  },
    {
    worked: "In Himalaya Robotics Club",
    job: "Graphic Designer",
    date: "2025-Present",
    contents: [
      "Design graphic posters for social media to promote events, workshops, and club activities.",
      "Create visually engaging layouts aligned with the club's technical and innovative identity.",
      "Collaborate with team members to communicate ideas clearly through effective visual design.",
    ],
  },
    {
    worked: "In Project Abhaya",
    job: "UI/UX & Graphic Designer (Internship)",
    date: "Aug 25 - Dec 25 2025",
    contents: [
      "Designed the official Project Abhaya website with a focus on usability and clarity.",
      "Worked from wireframes to final visual design to ensure a clean and consistent interface.",
      "Created graphic design posters for social media to support campaigns and digital communication.",
      "Collaborated with the team to translate ideas into clean, purpose-driven visual designs.",
      "Used Figma and Photoshop to bring the ideas of Project Abhaya to life.",
    ],
  },
  {
    worked: "In Milan Tara",
    job: "Graphic Designer",
    date: "2024-2025",
    contents: [
      "Designed visual templates for Starmap and Momentmap, maintaining brand consistency and visual clarity.",
      "Created reusable design systems and layouts in Adobe Illustrator to support product presentation and marketing needs.",
      "Worked closely with the team to refine designs based on product requirements and feedback.",
    ],
  }, 
];

export const reviews = [
  {
    name: "Jack",
    body: "I've never seen anything like this before. It's amazing. I love it.",
    img: "https://robohash.org/jack",
  },
  {
    name: "Jill",
    body: "I don't know what to say. I'm speechless. This is amazing.",
    img: "https://robohash.org/jill",
  },
  {
    name: "John",
    body: "I'm at a loss for words. This is amazing. I love it.",
    img: "https://robohash.org/john",
  },
  {
    name: "Alice",
    body: "This is hands down the best thing I've experienced. Highly recommend!",
    img: "https://robohash.org/alice",
  },
  {
    name: "Bob",
    body: "Incredible work! The attention to detail is phenomenal.",
    img: "https://robohash.org/bob",
  },
  {
    name: "Charlie",
    body: "This exceeded all my expectations. Absolutely stunning!",
    img: "https://robohash.org/charlie",
  },
  {
    name: "Dave",
    body: "Simply breathtaking. The best decision I've made in a while.",
    img: "https://robohash.org/dave",
  },
  {
    name: "Eve",
    body: "So glad I found this. It has changed the game for me.",
    img: "https://robohash.org/eve",
  },
];

export const projects = {
  all: [
    {
      id: 1,
      title: "Kumari: The Living Goddess",
      subtitle: "The Living Goddess",
      category: "Painting",
      img: "assets/projects/kumari_1.jpeg",
      gridClass: "grid-1",
      description: "A beautiful portrayal of the Living Goddess tradition in Nepal, capturing the essence of this sacred cultural practice.",
      longDescription: "Kumari: The Living Goddess is a deeply personal painting that explores the sacred Newar tradition of worshipping a pre-pubescent girl as the living incarnation of the goddess Taleju. Rooted in centuries of devotion, this piece captures the weight of divinity carried by a child — her gaze distant yet all-knowing, adorned in crimson and gold. The composition balances reverence and vulnerability, inviting the viewer into a spiritual space where myth and reality coexist. Created using layered acrylic washes and fine-detail brushwork, it took over three weeks to complete.",
      tags: ["Acrylic", "Canvas", "Fine Detail"],
      year: "2024",
      role: "Artist",
      subImages: [],
    },
    {
      id: 2,
      title: "Web Design:",
      subtitle: "Project Abhaya",
      category: "UI/UX",
      img: "/assets/projects/Abhaya.png",
      gridClass: "grid-2",
      description: "Complete website design for Project Abhaya focusing on user experience and accessibility.",
      longDescription: "Project Abhaya is a social initiative focused on spreading awareness and support for abuse survivors in Nepal. I was responsible for the end-to-end website design — starting from user research and wireframing to high-fidelity prototypes and final handoff. The design prioritizes clarity, emotional safety, and ease of navigation so that visitors in distress can find resources quickly. The color palette was intentionally calming, and typography choices were made to ensure readability across all devices. This project was built in Figma and later implemented with developer collaboration.",
      tags: ["Figma", "Photoshop", "Wireframing", "Prototyping"],
      year: "2025",
      role: "UI/UX Designer",
      href: "",
      subImages: [],
    },
    {
      id: 3,
      title: "F1: 3D Animation",
      category: "Animation",
      img: "/assets/projects/F1.png",
      gridClass: "grid-3",
      description: "A high-speed 3D animation of a Formula 1 car, exploring motion, light, and speed.",
      longDescription: "This F1 3D animation project was an exercise in pushing the limits of Blender's rendering and physics simulation capabilities. The goal was to recreate the visceral feeling of a Formula 1 car at full speed — the blur of the environment, the heat shimmer off the tarmac, the aerodynamic flex of the rear wing. Every detail from tire deformation to motion blur was carefully crafted. The final render was produced using Cycles renderer with HDRI lighting and custom compositing in After Effects to add depth of field and chromatic aberration effects.",
      tags: ["Blender", "After Effects", "Cycles Render", "Motion Blur"],
      year: "2024",
      role: "3D Animator",
      subImages: [],
    },
    {
      id: 4,
      title: "Inside The Art",
      category: "Motion Graphics",
      img: "/assets/projects/Endless.png",
      gridClass: "grid-4",
      description: "A compilation of motion graphics work from 2024 showcasing various animation techniques.",
      longDescription: "Inside The Art is a motion graphics project that takes the viewer on a journey through the creative process itself — layers peeling back, brushstrokes appearing in reverse, colors blooming from nothing. It was designed as both a personal showreel and a standalone piece exploring the relationship between static art and time. The piece uses a combination of After Effects keyframe animation, Illustrator vector work, and custom audio design to create a cohesive visual essay. Every transition was hand-crafted to feel organic rather than mechanical.",
      tags: ["After Effects", "Illustrator", "Motion Design", "Audio Sync"],
      year: "2024",
      role: "Motion Designer",
      subImages: [],
    },
    {
      id: 5,
      title: "Logo Design",
      category: "Graphic Design",
      img: "/assets/projects/wl.png",
      gridClass: "grid-5",
      description: "Complete branding solution for a local coffee shop including logo, packaging, and marketing materials.",
      longDescription: "This logo design project was a full branding exercise for a local coffee shop seeking a modern yet warm identity. The brief called for something that felt artisanal and approachable without being cliché. The final mark is a minimal wordmark paired with a custom icon that subtly integrates a coffee cup and a leaf — nodding to both the product and sustainability values. The typeface was custom-modified for unique character. Deliverables included primary and secondary logo variants, color palette, typography guide, and mockups for cups, packaging, and signage.",
      tags: ["Illustrator", "Branding", "Typography", "Packaging"],
      year: "2024",
      role: "Brand Designer",
      subImages: [],
    },
  ],

  painting: [
    {
      id: 1,
      title: "Kumari: The Living Goddess",
      subtitle: "The Living Goddess",
      category: "Painting",
      img: "/assets/projects/kumari_1.jpeg",
      gridClass: "grid-1",
      description: "A beautiful portrayal of the Living Goddess tradition in Nepal.",
      longDescription: "Kumari: The Living Goddess is a deeply personal painting that explores the sacred Newar tradition of worshipping a pre-pubescent girl as the living incarnation of the goddess Taleju. Rooted in centuries of devotion, this piece captures the weight of divinity carried by a child — her gaze distant yet all-knowing, adorned in crimson and gold. The composition balances reverence and vulnerability, inviting the viewer into a spiritual space where myth and reality coexist. Created using layered acrylic washes and fine-detail brushwork, it took over three weeks to complete.",
      tags: ["Acrylic", "Canvas", "Fine Detail"],
      year: "2024",
      role: "Artist",
      subImages: [
  '/assets/projects/kumari_2.jpg',
  '/assets/projects/kumari_3.jpg',
  '/assets/projects/kumari_4.jpg',
],
    },
    {
      id: 3,
      title: "Uljhan",
      category: "Painting",
      img: "/assets/projects/uljhan.jpg",
      gridClass: "grid-2",
      description: "An abstract exploration of complexity and emotions.",
      longDescription: "Uljhan — meaning 'entanglement' in Nepali/Hindi — is an abstract painting born from a period of personal uncertainty and mental noise. The canvas is layered with overlapping strokes, competing colors, and fragmented shapes that resist resolution. Rather than offering clarity, the piece invites the viewer to sit with complexity. Oil and mixed media were used to build up texture over multiple sessions, with no fixed composition planned from the start. The result is something raw and honest — a visual record of navigating confusion without forcing order.",
      tags: ["Oil", "Mixed Media", "Abstract", "Texture"],
      year: "2023",
      role: "Artist",
      subImages: [
  '/assets/projects/kumari_2.jpg',
  '/assets/projects/kumari_3.jpg',
  '/assets/projects/kumari_4.jpg',
],
    },
    {
      id: 6,
      title: "Abstract Dreams",
      category: "Painting",
      img: "/assets/projects/abstract.jpg",
      gridClass: "grid-3",
      description: "A vibrant abstract painting series exploring color theory and form.",
      longDescription: "Abstract Dreams is a series of paintings inspired by the visual logic of dreams — disjointed, vivid, emotionally charged. Each piece in the series isolates a specific emotional state and translates it through color temperature, stroke direction, and spatial composition. Warm hues push forward while cool tones recede, creating depth without perspective. The series was painted over six months and exhibited locally. It represents a deliberate study of how color alone can communicate mood and narrative without representation.",
      tags: ["Acrylic", "Color Theory", "Series", "Exhibition"],
      year: "2023",
      role: "Artist",
      subImages: [],
    },
  ],

  "ui-ux": [
    {
      id: 2,
      title: "Web Design:",
      subtitle: "Project Abhaya",
      category: "UI/UX",
      img: "/assets/projects/Abhaya.png",
      gridClass: "grid-1",
      description: "Complete website design for Project Abhaya focusing on user experience and accessibility.",
      longDescription: "Project Abhaya is a social initiative focused on spreading awareness and support for abuse survivors in Nepal. I was responsible for the end-to-end website design — starting from user research and wireframing to high-fidelity prototypes and final handoff. The design prioritizes clarity, emotional safety, and ease of navigation so that visitors in distress can find resources quickly. The color palette was intentionally calming, and typography choices were made to ensure readability across all devices.",
      tags: ["Figma", "Photoshop", "Wireframing", "Prototyping"],
      year: "2025",
      role: "UI/UX Designer",
      href: "",
      subImages: [],
    },
    {
      id: 7,
      title: "Mobile App:",
      subtitle: "EcoTracker",
      category: "UI/UX",
      img: "/assets/projects/ecotracker.jpg",
      gridClass: "grid-2",
      description: "Mobile app design for environmental tracking and carbon footprint monitoring.",
      longDescription: "EcoTracker is a concept mobile application designed to help individuals track their daily carbon footprint and receive actionable suggestions to reduce their environmental impact. The UX focused on making complex environmental data digestible and motivating for everyday users. The interface uses a green-forward palette, progress-based gamification, and micro-animations to encourage habitual check-ins. Designed entirely in Figma with interactive prototypes for user testing.",
      tags: ["Figma", "Mobile UI", "UX Research", "Prototyping"],
      year: "2024",
      role: "UI/UX Designer",
      subImages: [],
    },
    {
      id: 8,
      title: "Dashboard:",
      subtitle: "Analytics Pro",
      category: "UI/UX",
      img: "/assets/projects/dashboard.jpg",
      gridClass: "grid-3",
      description: "Data visualization dashboard design for business analytics.",
      longDescription: "Analytics Pro is a B2B SaaS dashboard concept designed for business owners who need clear, actionable insights from complex data sets. The challenge was organizing high data density without overwhelming users. The solution uses a modular card system, progressive disclosure of detail, and a strict typographic hierarchy to guide attention. Dark mode was the primary design target for reduced eye strain during extended sessions. Charts and graphs were designed with accessibility in mind, using patterns in addition to color to convey data differences.",
      tags: ["Figma", "Data Viz", "Dashboard", "Dark Mode"],
      year: "2024",
      role: "UI/UX Designer",
      subImages: [],
    },
  ],

  animation: [
    {
      id: 9,
      title: "3D Character:",
      subtitle: "Hero Animation",
      category: "Animation",
      img: "/assets/projects/3d-character.jpg",
      gridClass: "grid-1",
      description: "3D character animation for gaming with full rigging and expressions.",
      longDescription: "This 3D character project involved the full pipeline from concept to final render — modeling, UV unwrapping, texturing, rigging, and animation. The character is a stylized hero designed for a game prototype, with an expressive face rig capable of conveying a range of emotions. Walk cycles, combat stances, and idle animations were all produced. Particular attention was given to the weight and momentum of movement to ensure the character felt grounded and believable despite the stylized aesthetic.",
      tags: ["Blender", "Rigging", "Character Animation", "Game Asset"],
      year: "2024",
      role: "3D Artist & Animator",
      subImages: [],
    },
    {
      id: 10,
      title: "F1: 3D Animation",
      category: "Animation",
      img: "/assets/projects/F1.png",
      gridClass: "grid-2",
      description: "A high-speed 3D animation of a Formula 1 car exploring motion, light, and speed.",
      longDescription: "This F1 3D animation project was an exercise in pushing the limits of Blender's rendering and physics simulation capabilities. The goal was to recreate the visceral feeling of a Formula 1 car at full speed — the blur of the environment, the heat shimmer off the tarmac, the aerodynamic flex of the rear wing. Every detail from tire deformation to motion blur was carefully crafted. The final render was produced using Cycles renderer with HDRI lighting and custom compositing in After Effects.",
      tags: ["Blender", "After Effects", "Cycles Render", "Motion Blur"],
      year: "2024",
      role: "3D Animator",
      subImages: [],
    },
    {
      id: 15,
      title: "Character Rig",
      category: "Animation",
      img: "/assets/projects/character-rig.jpg",
      gridClass: "grid-3",
      description: "Professional character rigging setup for animation.",
      longDescription: "A technical deep-dive into professional character rigging, this project focused on building a clean, animator-friendly rig in Blender. The rig includes IK/FK switching for limbs, a custom spine system, facial shape keys for lip sync, and a control layer with intuitive handles. The goal was to create something that could be handed off to other animators without explanation — a rig that gets out of the way and lets creativity flow. Documented with a short technical breakdown video.",
      tags: ["Blender", "Rigging", "IK/FK", "Shape Keys"],
      year: "2024",
      role: "Rigger",
      subImages: [],
    },
  ],

  motion: [
    {
      id: 4,
      title: "Inside The Art",
      category: "Motion Graphics",
      img: "/assets/projects/Endless.png",
      gridClass: "grid-1",
      description: "A motion graphics piece exploring the creative process through animation.",
      longDescription: "Inside The Art is a motion graphics project that takes the viewer on a journey through the creative process itself — layers peeling back, brushstrokes appearing in reverse, colors blooming from nothing. It was designed as both a personal showreel and a standalone piece exploring the relationship between static art and time. The piece uses a combination of After Effects keyframe animation, Illustrator vector work, and custom audio design to create a cohesive visual essay.",
      tags: ["After Effects", "Illustrator", "Motion Design", "Audio Sync"],
      year: "2024",
      role: "Motion Designer",
      subImages: [],
    },
    {
      id: 11,
      title: "Brand Intro:",
      subtitle: "Tech Startup",
      category: "Motion Graphics",
      img: "/assets/projects/brand-intro.jpg",
      gridClass: "grid-2",
      description: "Animated brand introduction video for a tech startup.",
      longDescription: "This brand intro animation was created for a tech startup launching their product. The brief required something punchy, modern, and memorable — under 10 seconds, able to work with or without sound. The solution was a kinetic typography sequence with logo reveal, using sharp geometric transitions and a clean monochrome palette with a single accent color pop. Delivered in multiple formats for social media, website hero, and presentation use. Produced entirely in After Effects with custom expressions for smooth motion.",
      tags: ["After Effects", "Kinetic Typography", "Brand Motion", "Logo Reveal"],
      year: "2024",
      role: "Motion Designer",
      subImages: [],
    },
    {
      id: 16,
      title: "Motion Reel 2024",
      category: "Motion Graphics",
      img: "/assets/projects/motion-reel.jpg",
      gridClass: "grid-3",
      description: "A curated showreel of motion graphics work from 2024.",
      longDescription: "The 2024 Motion Reel is a curated compilation of motion graphics and animation work produced throughout the year. It spans brand animations, title sequences, UI motion studies, and experimental pieces. The reel itself was designed as a piece of work — every cut is deliberate, synced to a custom audio track, and showcases a specific skill or technique. It serves as both a professional portfolio tool and a personal milestone marker for the year's creative output.",
      tags: ["After Effects", "Premiere Pro", "Showreel", "Compilation"],
      year: "2024",
      role: "Motion Designer",
      subImages: [],
    },
  ],

  graphics: [
    {
      id: 5,
      title: "Logo Design",
      category: "Graphic Design",
      img: "/assets/projects/wl.png",
      gridClass: "grid-1",
      description: "Complete branding solution including logo, packaging, and marketing materials.",
      longDescription: "This logo design project was a full branding exercise for a local coffee shop seeking a modern yet warm identity. The brief called for something that felt artisanal and approachable without being cliché. The final mark is a minimal wordmark paired with a custom icon that subtly integrates a coffee cup and a leaf — nodding to both the product and sustainability values. The typeface was custom-modified for unique character. Deliverables included primary and secondary logo variants, color palette, typography guide, and mockups.",
      tags: ["Illustrator", "Branding", "Typography", "Packaging"],
      year: "2024",
      role: "Brand Designer",
      subImages: [],
    },
    {
      id: 12,
      title: "Poster Design",
      category: "Graphic Design",
      img: "/assets/projects/Maria Corina.jpg",
      gridClass: "grid-2",
      description: "Bold editorial poster design for a political campaign.",
      longDescription: "This poster was designed as part of a political campaign series, balancing strong portraiture with bold typographic layout. The design needed to communicate authority, hope, and clarity simultaneously — working both at large-format print scale and compressed social media sizes. The approach uses high-contrast photography treatment, a restricted two-color palette, and oversized display type to create immediate visual impact. All photography retouching and layout was handled in Photoshop and Illustrator.",
      tags: ["Photoshop", "Illustrator", "Editorial", "Print Design"],
      year: "2024",
      role: "Graphic Designer",
      subImages: [],
    },
    {
      id: 17,
      title: "Poster Design",
      category: "Graphic Design",
      img: "/assets/projects/El.jpg",
      gridClass: "grid-3",
      description: "Expressive poster design with bold visual language.",
      longDescription: "This poster project explored expressive visual communication through bold composition, mixed typography, and experimental image treatment. The brief was open-ended, allowing full creative freedom to push beyond conventional layout. The result is a piece that sits between fine art and graphic design — using distortion, layering, and contrast to create tension and intrigue. Designed in Photoshop with custom texture overlays and hand-drawn elements scanned and composited into the final piece.",
      tags: ["Photoshop", "Illustrator", "Experimental", "Mixed Media"],
      year: "2024",
      role: "Graphic Designer",
      subImages: [],
    },
  ],
};