export const mySocials = [
  {
    name: "Github",
    href: "https://github.com/Hell086",
    icon: "/assets/socials/github.svg",
  },
  {
    name: "Linkedin",
    href: "https://www.linkedin.com/in/binay-shrestha-bbbbb52a5/",
    icon: "/assets/socials/linkedin.svg",
  },
  {
    name: "Instagram",
    href: "https://www.instagram.com/binayx_art/",
    icon: "/assets/socials/instagram.svg",
  },
];

export const experiences = [
   {
    worked: "In Project Abhaya",
    job: "UI/UX & Graphic Designer (Internship)",
    date: "Aug 25 - Dec 25 2025",
    contents: [
      "Designed the official Project Abhaya website with a focus on usability and clarity.",
      "Worked from wireframes to final visual design to ensure a clean and consistent interface.",
      "Created graphic design posters for social media to support campaigns and digital communication.",
      "Collaborated with the team to translate ideas into clean, purpose-driven visual designs.",
      "Used Figma and Photoshop to bring the ideas of Project Abhaya to life.",
    ],
  },
    {
    worked: "In Himalaya Robotics Club",
    job: "Graphic Designer",
    date: "2025-Present",
    contents: [
      "Design graphic posters for social media to promote events, workshops, and club activities.",
      "Create visually engaging layouts aligned with the club's technical and innovative identity.",
      "Collaborate with team members to communicate ideas clearly through effective visual design.",
    ],
  },
    {
    worked: "In Milan Tara",
    job: "Graphic Designer",
    date: "2024-2025",
    contents: [
      "Designed visual templates for Starmap and Momentmap, maintaining brand consistency and visual clarity.",
      "Created reusable design systems and layouts in Adobe Illustrator to support product presentation and marketing needs.",
      "Worked closely with the team to refine designs based on product requirements and feedback.",
    ],
  },
  {
    worked: "Freelance",
    job: "Artist",
    date: "2018-Present",
    contents: [
      "I began my professional artistic journey in 2018, focusing on commission-based artworks that allowed me to connect directly with collectors and art enthusiasts. Over time, I expanded my practice, creating not only personal work but also mural artworks that brought spaces to life with colors, form, and storytelling. Each piece I created was a step in refining my style and understanding what resonates with people.",
      "Along the way, I collaborated with fellow artists on various projects, exchanging ideas and pushing creative boundaries. Through selling my art and completing commissions, I was able to turn my passion into a sustainable career while building a supportive community that follows and values my artistic growth. This journey has been a blend of exploration, collaboration, and dedication, shaping me into the professional artist I am today.",
    ],
  }, 
];

export const reviews = [
  {
    name: "Jack",
    body: "I've never seen anything like this before. It's amazing. I love it.",
    img: "https://robohash.org/jack",
  },
  {
    name: "Jill",
    body: "I don't know what to say. I'm speechless. This is amazing.",
    img: "https://robohash.org/jill",
  },
  {
    name: "John",
    body: "I'm at a loss for words. This is amazing. I love it.",
    img: "https://robohash.org/john",
  },
  {
    name: "Alice",
    body: "This is hands down the best thing I've experienced. Highly recommend!",
    img: "https://robohash.org/alice",
  },
  {
    name: "Bob",
    body: "Incredible work! The attention to detail is phenomenal.",
    img: "https://robohash.org/bob",
  },
  {
    name: "Charlie",
    body: "This exceeded all my expectations. Absolutely stunning!",
    img: "https://robohash.org/charlie",
  },
  {
    name: "Dave",
    body: "Simply breathtaking. The best decision I've made in a while.",
    img: "https://robohash.org/dave",
  },
  {
    name: "Eve",
    body: "So glad I found this. It has changed the game for me.",
    img: "https://robohash.org/eve",
  },
];

export const projects = {
  all: [
    {
      id: 1,
      title: "Kumari: The Living Goddess",
      category: "Painting",
      img: "/assets/projects/Painting/kumari_1.jpeg",
      heroImg: "/assets/projects/Painting/Kumari_hero.jpeg",
      gridClass: "grid-1",
      description: "A beautiful portrayal of the Living Goddess tradition in Nepal, capturing the essence of this sacred cultural practice.",
      longDescription: "Kumari: The Living Goddess is a deeply personal painting that explores the sacred Newar tradition of worshipping a pre-pubescent girl as the living incarnation of the goddess Taleju. Rooted in centuries of devotion, this piece captures the weight of divinity carried by a child — her gaze distant yet all-knowing, adorned in crimson and gold. The composition balances reverence and vulnerability, inviting the viewer into a spiritual space where myth and reality coexist. Created using layered acrylic washes and fine-detail brushwork, it took over three weeks to complete.",
      tags: ["Acrylic Color", "Canvas","Brush"],
      year: "2025",
      //role: "Artist",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "This painting explores the story of the Kumari, not only as a revered living goddess but also as a young girl who grows up within a tradition that places unique responsibilities and expectations upon her. I wanted to portray the contrast between her divine identity and her natural desire to experience an ordinary childhood. The two lotus flowers in the background are central to the concept. The lotus on the left is still waiting to bloom, representing her life as a Kumari the experiences, restrictions, sacrifices, sadness, and emotions she may go through at such a young age. It also represents the part of her that may wish to stay, play, grow, and live like any other child. The fully bloomed lotus on the right represents the life after her time as a Kumari, when she returns to ordinary life, continues to grow, and has the opportunity to experience life more freely. Together, the two lotus flowers symbolize a journey from childhood through the Kumari tradition and eventually into a new stage of life." },
        creativeIntent: { title: "Creative Intent", content: "I had always wanted to create a painting of the Kumari as one of the most realistic and ambitious paintings I had made. Before beginning this work, I researched the Kumari tradition, including its origins in Nepal, the beliefs and myths surrounding it, and its cultural significance. During my research, I read From Goddess to Mortal: The True Life Story of Kumari by Rashmila Shakya, a memoir that provided a personal perspective on the experience of growing up as a Kumari. Her experiences helped me understand the rituals, isolation, societal expectations, and transition from being worshipped as a goddess to returning to an ordinary life. For this painting, I chose Nihira Bajracharya, the Kumari of Patan, Lalitpur, as my subject. When I first came across her image, I felt something different in her expression and presence. I was drawn to the contrast between her young age and the powerful cultural identity she represents, and that feeling eventually inspired me to choose her as the subject of this project. Through this painting, I wanted viewers to look beyond the title of “Kumari” and see the young person behind the goddess." },
        visualDirection: { title: "Visual Direction", content: "I chose a predominantly blue background to create a cool and somewhat cold atmosphere, reflecting the more quiet, distant, and contemplative aspects of the story. The blue also creates a strong visual contrast with the red and orange tones of her traditional clothing, allowing the figure to stand out from the background. The warm colors of her dress bring richness, cultural identity, and a sense of sacredness to the composition, while the cooler background creates an emotional balance. The combination of the blue background, warm clothing, and two lotus flowers was intended to create a visually pleasing composition while reinforcing the emotional journey represented in the painting." },
        process: { title: "Process", content: "I began the painting by carefully sketching the portrait using the grid method to achieve accurate proportions and capture the features of my subject. After completing the initial drawing, I created an underpainting using burnt sienna to establish the basic values and warmth of the portrait. I then gradually built the painting using acrylic colors, working through multiple layers to develop realistic skin tones, facial features, clothing, ornaments, light, and shadows. I focused on building the details slowly while maintaining the natural expression and realistic appearance of the subject. The entire painting took approximately 20 days to complete, making it one of the most detailed and time-intensive realistic paintings I have created." },
        finalOutcome: { title: "Final Artwork" },
      },
      subImages: [
        "/assets/projects/Painting/Kumari.jpeg",
        "/assets/projects/Painting/Kumari_hero.jpeg",
        "/assets/projects/Painting/Kumari_2.jpeg",
        "/assets/projects/Painting/Kumarieye.jpeg",
        "/assets/projects/Painting/Nihira Bajaracharya.jpeg",
      ],
    },
    {
      id: 2,
      title: "Web Design:",
      category: "UI/UX Design",
      img: "/assets/projects/Project Abhaya/Abhaya.png",
      gridClass: "grid-2",
      description: "Complete website design for Project Abhaya focusing on user experience and accessibility.",
      longDescription: "Project Abhaya is a social initiative focused on spreading awareness and support for abuse survivors in Nepal. I was responsible for the end-to-end website design — starting from user research and wireframing to high-fidelity prototypes and final handoff. The design prioritizes clarity, emotional safety, and ease of navigation so that visitors in distress can find resources quickly. The color palette was intentionally calming, and typography choices were made to ensure readability across all devices. This project was built in Figma and later implemented with developer collaboration.",
      tags: ["Figma"],
      year: "2025",
      role: "UI/UX Designer",
      href: "",
      projectLink: "https://www.figma.com/design/iaHK2wJ0BuId9qZEaIp3mZ/Abhaya-Web-design?node-id=0-1&t=SeVTt5pfspZQezZP-1",
      caseStudyContent: {
        projectOverview: { title: "Project Overview", content: "During my 4-month web design internship at Project Abhaya, I designed the organization's website in Figma based on team requirements and existing brand guidelines. I worked on the overall website structure, including the landing page, navigation, Our Work, E-Learning, and Get Involved sections. The project started with team discussions and requirement gathering, followed by brainstorming, research, and design exploration. Through this process, I learned how to turn real project requirements into a user-friendly website structure, work within brand guidelines, collaborate with a team, and design with users' navigation and accessibility in mind." },
        designGoal: { title: "Design Goal", content: "The goal was to create a clear and user-friendly website where visitors could understand Project Abhaya and its work, explore the organization's journey and impact, access educational resources, discover ways to get involved, and navigate the website without confusion." },
        uxVisualDirection: { title: "UX & Visual Direction", content: "I gathered and documented requirements through discussions with the Project Abhaya team before starting the design. I researched women's empowerment and social organization websites, including UN Women, and explored Pinterest and AI tools for layout and visual inspiration. The final direction followed Project Abhaya's brand guidelines, with navigation and content structured to make important information easy to find and access." },
        designProcess: { title: "Design Process", content: "The process began with requirement gathering, brainstorming, and layout exploration. In Figma, I designed the landing page, Our Work, E-Learning, and Get Involved sections, including resource categories and ways for visitors to participate. I refined layouts and navigation based on team requirements while maintaining the brand guidelines and keeping the experience simple to use." },
        finalOutcome: { title: "Final Design" },
      },
      subImages: [
        "/assets/projects/Project Abhaya/PAherosection.png",
        "/assets/projects/Project Abhaya/PAjourney.png",
        "/assets/projects/Project Abhaya/PAelearning.png",
      ],
    },
    {
      id: 7,
      title: "Ps exploration",
      category: "Digital Art",
      img: "/assets/projects/Digital Art/flower.png",
      gridClass: "grid-3",
      description: "A high-speed 3D animation of a Formula 1 car, exploring motion, light, and speed.",
      longDescription: "This F1 3D animation project was an exercise in pushing the limits of Blender's rendering and physics simulation capabilities. The goal was to recreate the visceral feeling of a Formula 1 car at full speed — the blur of the environment, the heat shimmer off the tarmac, the aerodynamic flex of the rear wing. Every detail from tire deformation to motion blur was carefully crafted. The final render was produced using Cycles renderer with HDRI lighting and custom compositing in After Effects to add depth of field and chromatic aberration effects.",
      tags: ["Adobe Photoshop"],
      year: "2026",
      //role: "3D Animator",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "This 3D animation explores the visceral feeling of a Formula 1 car at full speed through motion, light, and environmental detail." },
        //creativeDirection: { title: "Creative Direction", content: "The focus was recreating the sense of speed through details such as tire deformation, heat shimmer, and aerodynamic movement." },
        //visualDirection: { title: "Visual Direction", content: "Motion blur, depth of field, chromatic aberration, HDRI lighting, and the car's rear-wing movement shape the final visual language." },
        //animationProcess: { title: "Animation Process", content: "The animation was developed in Blender with Cycles rendering, then composited in After Effects to refine the final image." },
        finalOutcome: { title: "Final Art"},
      },
      subImages: [
        "/assets/projects/Digital Art/Deadflower.png",
        "/assets/projects/Digital Art/flower.png",
        "/assets/projects/Digital Art/key.png",
        "/assets/projects/Digital Art/learn.png",
        "/assets/projects/Digital Art/Artpasal.png",
      ],
    },
    
    {
      id: 4,
      title: "Inside The Art",
      category: "Animation & Motion Graphics",
      img: "/assets/projects/Endless.png",
      gridClass: "grid-4",
      description: "A compilation of motion graphics work from 2024 showcasing various animation techniques.",
      longDescription: "Inside The Art is a motion graphics project that takes the viewer on a journey through the creative process itself — layers peeling back, brushstrokes appearing in reverse, colors blooming from nothing. It was designed as both a personal showreel and a standalone piece exploring the relationship between static art and time. The piece uses a combination of After Effects keyframe animation, Illustrator vector work, and custom audio design to create a cohesive visual essay. Every transition was hand-crafted to feel organic rather than mechanical.",
      tags: ["After Effects" ],
      year: "2024",
      //role: "Motion Designer",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "Inside the Art was created from a long standing fascination I have with the idea of stepping inside a painting and experiencing the world that exists within it. While learning Adobe After Effects through YouTube tutorials, I decided to experiment with this idea by creating a motion graphic that makes it feel as though the viewer can move beyond the surface of an artwork and enter its world. Although this was primarily a learning project, it allowed me to explore how a static painting can be transformed into an immersive visual experience through motion, depth, and animation. The process of creating this effect was both challenging and exciting, and it helped me discover how motion graphics can give a completely different life to a still artwork." },
        //creativeDirection: { title: "Creative Direction", content: "It was made both as a personal showreel and as a standalone exploration of the relationship between static art and time." },
        //visualDirection: { title: "Visual Direction", content: "After Effects animation, Illustrator vector work, and custom audio design create an organic visual essay rather than a mechanical sequence." },
        //animationProcess: { title: "Animation Process", content: "Each transition was hand-crafted and timed to create a cohesive journey through the creative process." },
        finalOutcome: { title: "Final Animation", video: "/assets/videos/3D camera animation.mp4" },
      },
      subImages: [],
    },
    {
      id: 5,
      title: "Wind Logo Design",
      category: "Graphic Design",
      img: "/assets/projects/Logo design/wl.png",
      gridClass: "grid-5",
      description: "Complete branding solution for a local coffee shop including logo, packaging, and marketing materials.",
      longDescription: "This logo design project was a full branding exercise for a local coffee shop seeking a modern yet warm identity. The brief called for something that felt artisanal and approachable without being cliché. The final mark is a minimal wordmark paired with a custom icon that subtly integrates a coffee cup and a leaf — nodding to both the product and sustainability values. The typeface was custom-modified for unique character. Deliverables included primary and secondary logo variants, color palette, typography guide, and mockups for cups, packaging, and signage.",
      tags: ["Adobe Illustrator"],
      year: "2025",
      //role: "Brand Designer",
      caseStudyContent: {
        conceptBackground: { title: "Concept & Background", content: "Wind is a logo created for my personal design page on social media, where I showcase my creative and design work. The name “Wind” was suggested by my sister and became the identity of the page. The logo represents the idea of wind through a simple, flowing form that can also work as a recognizable brand icon." },
        creativeIntent: { title: "Creative Intent", content: "I wanted the logo to feel free, natural, and dynamic, reflecting the continuous movement of wind. The goal was to create a simple symbol that could represent creativity and movement while remaining easy to recognize and use across my design page." },
        visualDirection: { title: "Visual Direction", content: "The visual direction is based on a flowing wind-like shape, using smooth curves and a minimal form to create a sense of natural movement. The design was kept simple so the symbol could work effectively as both a logo and a standalone brand icon." },
        designProcess: { title: "Design Process", content: "I started by sketching multiple logo ideas on paper and explored different flowing forms through several iterations. After nearly two days of exploration, I finalized the direction that best represented the idea of wind. I then recreated and refined the final logo digitally in Adobe Illustrator, using the Pen Tool to create the curves and achieve a clean, polished shape." },
        finalOutcome: { title: "Final Identity" },
      },
      subImages: ["/assets/projects/Logo design/W.png",
        "/assets/projects/Logo design/wl.png",
        "/assets/projects/Logo design/wl2.png"
      ],
    },
  ],

  painting: [
    {
      id: 1,
      title: "Kumari: The Living Goddess",
      subtitle: "The Living Goddess",
      category: "Painting",
      img: "/assets/projects/Painting/kumari_1.jpeg",
      gridClass: "grid-1",
      description: "A beautiful portrayal of the Living Goddess tradition in Nepal.",
      longDescription: "Kumari:  ",
      tags: ["Acrylic", "Canvas", "Fine Detail"],
      year: "2025",
      //role: "Artist",
      subImages: [
        "/assets/projects/Painting/Kumari.jpeg",
        "/assets/projects/Painting/Kumari_hero.jpeg",
        "/assets/projects/Painting/Kumari_2.jpeg",
        "/assets/projects/Painting/Kumarieye.jpeg",
        "/assets/projects/Painting/Nihira Bajaracharya.jpeg",
      ],
    },
    //{
    //   id: 13,
    //   title: "Uljhan",
    //   category: "Painting",
    //   img: "/assets/projects/uljhan.jpg",
    //   gridClass: "grid-2",
    //   description: "An abstract exploration of complexity and emotions.",
    //   longDescription: "Uljhan — meaning 'entanglement' in Nepali/Hindi — is an abstract painting born from a period of personal uncertainty and mental noise. The canvas is layered with overlapping strokes, competing colors, and fragmented shapes that resist resolution. Rather than offering clarity, the piece invites the viewer to sit with complexity. Oil and mixed media were used to build up texture over multiple sessions, with no fixed composition planned from the start. The result is something raw and honest — a visual record of navigating confusion without forcing order.",
    //   tags: ["Oil", "Mixed Media", "Abstract", "Texture"],
    //   year: "2023",
    //   role: "Artist",
    //   caseStudyContent: {
    //     conceptStory: { title: "Concept & Story", content: "Uljhan, meaning entanglement in Nepali and Hindi, is an abstract painting from a period of personal uncertainty and mental noise." },
    //     creativeIntent: { title: "Creative Intent", content: "Rather than resolving the uncertainty, the work invites the viewer to sit with complexity." },
    //     visualDirection: { title: "Visual Direction", content: "Overlapping strokes, competing colours, fragmented shapes, and built-up texture create a raw visual record of that experience." },
    //     process: { title: "Process", content: "Oil and mixed media were layered over multiple sessions without a fixed composition planned from the start." },
    //     finalOutcome: { title: "Final Artwork" },
    //   },
    //   subImages: [],
    // },
  ],

  "ui-ux": [
    {
      id: 2,
      title: "Web Design:",
      subtitle: "Project Abhaya",
      category: "UI/UX",
      img: "/assets/projects/Abhaya.png",
      gridClass: "grid-1",
      description: "Complete website design for Project Abhaya focusing on user experience and accessibility.",
      longDescription: "Project Abhaya is a social initiative focused on spreading awareness and support for abuse survivors in Nepal. I was responsible for the end-to-end website design — starting from user research and wireframing to high-fidelity prototypes and final handoff. The design prioritizes clarity, emotional safety, and ease of navigation so that visitors in distress can find resources quickly. The color palette was intentionally calming, and typography choices were made to ensure readability across all devices.",
      tags: ["Figma", "Photoshop", "Wireframing", "Prototyping"],
      year: "2025",
      //role: "UI/UX Designer",
      href: "",
      projectLink: "https://www.figma.com/design/iaHK2wJ0BuId9qZEaIp3mZ/Abhaya-Web-design?node-id=0-1&t=SeVTt5pfspZQezZP-1",
      subImages: [],
    },
  ],

  "digital art" : [
     {
      id: 3,
      title: "Lotus",
      category: "Digital Art",
      img: "/assets/projects/Digital Art/Lotus22.png",
      gridClass: "grid-1",
      description: "A lotus inspired by my Kumari painting, symbolizing purity, beauty, and spirituality.",
      //longDescription: "This F1 3D animation project was an exercise in pushing the limits of Blender's rendering and physics simulation capabilities. The goal was to recreate the visceral feeling of a Formula 1 car at full speed — the blur of the environment, the heat shimmer off the tarmac, the aerodynamic flex of the rear wing. Every detail from tire deformation to motion blur was carefully crafted. The final render was produced using Cycles renderer with HDRI lighting and custom compositing in After Effects to add depth of field and chromatic aberration effects.",
      tags: ["Adobe Photoshop"],
      year: "2026",
      //role: "3D Animator",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "This lotus artwork was created from a detail in my Kumari painting, which I originally created in Photoshop. While working on the painting, I was drawn to the lotus as more than just a decorative element it represents purity, beauty, spirituality, and divine presence, making it a meaningful symbol within the artwork. I wanted to give this small but significant element its own identity, so I isolated and reimagined the lotus as a standalone piece designed specifically for art prints. In this way, the artwork carries a fragment of the original Kumari painting while becoming a new piece with its own story, allowing the symbolism and beauty of the lotus to be appreciated on its own." },
        //creativeDirection: { title: "Creative Direction", content: "The focus was recreating the sense of speed through details such as tire deformation, heat shimmer, and aerodynamic movement." },
        //visualDirection: { title: "Visual Direction", content: "Motion blur, depth of field, chromatic aberration, HDRI lighting, and the car's rear-wing movement shape the final visual language." },
        //animationProcess: { title: "Animation Process", content: "The animation was developed in Blender with Cycles rendering, then composited in After Effects to refine the final image." },
        finalOutcome: { title: "Final Art"},
      },
      subImages: [
        "/assets/projects/Digital Art/Lotus2.png",
        "/assets/projects/Digital Art/Blue and white.jpg",
        "/assets/projects/Digital Art/lotus1.jpg",
        
      ],
    },
    {
      id: 6,
      title: "Illustrations",
      category: "Digital Art",
      img: "/assets/projects/Digital Art/berry2.jpg",
      gridClass: "grid-2",
      description: "A collection of my early digital artworks created in Adobe Fresco, exploring layers, lighting, shadows, and digital painting techniques.",
      //longDescription: "This F1 3D animation project was an exercise in pushing the limits of Blender's rendering and physics simulation capabilities. The goal was to recreate the visceral feeling of a Formula 1 car at full speed — the blur of the environment, the heat shimmer off the tarmac, the aerodynamic flex of the rear wing. Every detail from tire deformation to motion blur was carefully crafted. The final render was produced using Cycles renderer with HDRI lighting and custom compositing in After Effects to add depth of field and chromatic aberration effects.",
      tags: ["Adobe Fresco"],
      year: "2026",
      //role: "3D Animator",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "When I started learning digital art, I used **Adobe Fresco** to explore and practice digital illustration. These artworks were created with references from Pinterest and helped me understand the fundamentals of digital art. Through the process, I learned how to work with **layers, lighting, shadows, and depth**, while experimenting with different brushes and techniques. These early experiments gave me a strong foundation in digital art and helped me build confidence in developing my own digital artwork." },
        //creativeDirection: { title: "Creative Direction", content: "The focus was recreating the sense of speed through details such as tire deformation, heat shimmer, and aerodynamic movement." },
        //visualDirection: { title: "Visual Direction", content: "Motion blur, depth of field, chromatic aberration, HDRI lighting, and the car's rear-wing movement shape the final visual language." },
        //animationProcess: { title: "Animation Process", content: "The animation was developed in Blender with Cycles rendering, then composited in After Effects to refine the final image." },
        finalOutcome: { title: "Final Art"},
      },
      subImages: [
        "/assets/projects/Digital Art/berry2.jpg",
        "/assets/projects/Digital Art/pati2.jpg",
        "/assets/projects/Digital Art/2lolipop.jpg",
        "/assets/projects/Digital Art/Sunflower.jpg",
      ],
    },
    {
      id: 7,
      title: "PS exploration",
      category: "Digital Art",
      img: "/assets/projects/Digital Art/flower.png",
      gridClass: "grid-3",
      description: "Early Photoshop sketches focused on learning the interface, brushes, layers, and digital outlining techniques.",
      //longDescription: "This F1 3D animation project was an exercise in pushing the limits of Blender's rendering and physics simulation capabilities. The goal was to recreate the visceral feeling of a Formula 1 car at full speed — the blur of the environment, the heat shimmer off the tarmac, the aerodynamic flex of the rear wing. Every detail from tire deformation to motion blur was carefully crafted. The final render was produced using Cycles renderer with HDRI lighting and custom compositing in After Effects to add depth of field and chromatic aberration effects.",
      tags: ["Adobe Photoshop"],
      year: "2026",
      //role: "3D Animator",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "After moving to **Adobe Photoshop**, I focused on becoming familiar with its interface and digital drawing tools. Instead of immediately working with colors, I used this stage to practice creating **sketches and clean outlines**, allowing me to understand brushes, layers, and basic workflow. This approach helped me become more comfortable with Photoshop and build a stronger foundation before moving into more detailed and fully colored digital artworks." },
        //creativeDirection: { title: "Creative Direction", content: "The focus was recreating the sense of speed through details such as tire deformation, heat shimmer, and aerodynamic movement." },
        //visualDirection: { title: "Visual Direction", content: "Motion blur, depth of field, chromatic aberration, HDRI lighting, and the car's rear-wing movement shape the final visual language." },
        //animationProcess: { title: "Animation Process", content: "The animation was developed in Blender with Cycles rendering, then composited in After Effects to refine the final image." },
        finalOutcome: { title: "Final Art"},
      },
      subImages: [
        "/assets/projects/Digital Art/Deadflower.png",
        "/assets/projects/Digital Art/flower.png",
        "/assets/projects/Digital Art/key.png",
        "/assets/projects/Digital Art/learn.png",
      ],
    },
  ],

  motion: [
    {
      id: 4,
      title: "Inside The Art",
      category: "Motion Graphics",
      img: "/assets/projects/Endless.png",
      gridClass: "grid-1",
      description: "A compilation of motion graphics work from 2024 showcasing various animation techniques.",
      longDescription: "Inside The Art is a motion graphics project that takes the viewer on a journey through the creative process itself — layers peeling back, brushstrokes appearing in reverse, colors blooming from nothing. It was designed as both a personal showreel and a standalone piece exploring the relationship between static art and time. The piece uses a combination of After Effects keyframe animation, Illustrator vector work, and custom audio design to create a cohesive visual essay. Every transition was hand-crafted to feel organic rather than mechanical.",
      tags: ["After Effects", "Illustrator", "Motion Design", "Audio Sync"],
      year: "2024",
      //role: "Motion Designer",
      caseStudyContent: {
        conceptStory: { title: "Concept & Story", content: "Inside " },
        creativeDirection: { title: "Creative Direction", content: "It was made both as a personal showreel and as a standalone exploration of the relationship between static art and time." },
        visualDirection: { title: "Visual Direction", content: "After Effects animation, Illustrator vector work, and custom audio design create an organic visual essay rather than a mechanical sequence." },
        animationProcess: { title: "Animation Process", content: "Each transition was hand-crafted and timed to create a cohesive journey through the creative process." },
        finalOutcome: { title: "Final Animation", video: "/assets/videos/3D camera animation.mp4" },
      },
      subImages: [],
    },
  ],

  graphics: [
    {
      id: 5,
      title: "Logo Design",
      category: "Graphic Design",
      img: "/assets/projects/Logo design/wl.png",
      gridClass: "grid-1",
      description: "Complete branding solution including logo, packaging, and marketing materials.",
      longDescription: "This logo design project was a full branding exercise for a local coffee shop seeking a modern yet warm identity. The brief called for something that felt artisanal and approachable without being cliché. The final mark is a minimal wordmark paired with a custom icon that subtly integrates a coffee cup and a leaf — nodding to both the product and sustainability values. The typeface was custom-modified for unique character. Deliverables included primary and secondary logo variants, color palette, typography guide, and mockups.",
      tags: ["Illustrator", "Branding", "Typography", "Packaging"],
      year: "2025",
      //role: "Brand Designer",
      subImages: ["/assets/projects/Logo design/W.png",
        "/assets/projects/wl.png",
      ],
    },
    {
      id: 12,
      title: "Maria Corina poster",
      category: "Graphic Design",
      img: "/assets/projects/Maria Corina.jpg",
      gridClass: "grid-2",
      description: "Bold editorial poster design for a political campaign.",
      longDescription: "This poster was designed as part of a political campaign series, balancing strong portraiture with bold typographic layout. The design needed to communicate authority, hope, and clarity simultaneously — working both at large-format print scale and compressed social media sizes. The approach uses high-contrast photography treatment, a restricted two-color palette, and oversized display type to create immediate visual impact. All photography retouching and layout was handled in Photoshop and Illustrator.",
      tags: ["Figma"],
      year: "2025",
      //role: "Graphic Designer",
      href: "",
      projectLink: "https://www.figma.com/design/i3AJY2F6li0sjEydizLlFl/Binay-Shrestha?node-id=52-72&t=ySPai1Zr1UAYXxvA-1",
      caseStudyContent: {
        conceptPurpose: { title: "Concept & Purpose", content: "This poster was created as a visual design study for Maria Corina Machado, with the goal of communicating the subject through a clear and visually engaging composition. I explored different ways to organize the text, imagery, and overall layout while keeping the main message easy to understand." },
        creativeIntent: { title: "Creative Intent", content: "The design was intended to create immediate impact while keeping the message direct at very different viewing sizes.I wanted the design to feel balanced, clear, and visually strong rather than simply placing elements on the page. The main focus was on creating a composition where typography and imagery worked together to guide the viewer's attention." },
        visualDirection: { title: "Visual Direction", content: "The visual direction focused on typography, grid, alignment, spacing, hierarchy, and image composition. I explored how these design principles could create better balance and make the important information stand out clearly." },
        designProcess: { title: "Design Process", content: "I created four different versions of the poster in Figma, experimenting with different layouts and compositions. The earlier version lacked proper alignment and balance, so through each iteration I refined the typography, grid, spacing, image placement, and overall composition. The final version applied these design principles more effectively, resulting in a cleaner and more balanced poster." },
        finalOutcome: { title: "Final Design" },
      },
      subImages: ["/assets/projects/Maria Corina.jpg"],
    },
    {
      id: 17,
      title: "Voter list poster",
      category: "Graphic Design",
      img: "/assets/projects/El.jpg",
      gridClass: "grid-3",
      description: "Expressive poster design with bold visual language.",
      longDescription: "This poster project explored expressive visual communication through bold composition, mixed typography, and experimental image treatment. The brief was open-ended, allowing full creative freedom to push beyond conventional layout. The result is a piece that sits between fine art and graphic design — using distortion, layering, and contrast to create tension and intrigue. Designed in Photoshop with custom texture overlays and hand-drawn elements scanned and composited into the final piece.",
      tags: ["Figma"],
      year: "2025",
      //role: "Graphic Designer",
       href: "",
      projectLink: "https://www.figma.com/design/i3AJY2F6li0sjEydizLlFl/Binay-Shrestha?node-id=52-72&t=ySPai1Zr1UAYXxvA-1",
      caseStudyContent: {
        conceptPurpose: { title: "Concept & Purpose", content: "The purpose of this poster was to clearly guide viewers on how to check whether they have completed their voter registration and how to find their name on the voter list website." },
        creativeIntent: { title: "Creative Intent", content: "I wanted to make the information simple and easy to follow, so viewers could understand the process without feeling overwhelmed by the amount of information." },
        visualDirection: { title: "Visual Direction", content: "The design uses a long blue wave-like line as a visual guide, leading the viewer through each step of the process. I also used proper text alignment, spacing, and hierarchy to organize the information and make each step easy to read and follow." },
        designProcess: { title: "Design Process", content: "I focused on organizing the steps in a clear visual sequence and used the blue line to connect each stage of the process. I refined the alignment, spacing, typography, and placement of visual elements to create a clean layout that allows viewers to naturally follow the instructions from one step to the next." },
        finalOutcome: { title: "Final Design" },
      },
      subImages: ["/assets/projects/E.jpg",
        "/assets/projects/1.2.jpg",
        "/assets/projects/1.3.jpg",
        "/assets/projects/1.4.jpg",
        "/assets/projects/1.5.jpg"
      ],
    },
  ],
};
