/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: alban (https://sketchfab.com/alban)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bob-ross-painting-00a57bbd1c894a7cb9e45ec396a8f660
Title: Bob Ross painting
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useAnimations } from 'motion/react';

export function Painting(props) {
  const { nodes, materials } = useGLTF('/models/bob_ross_painting.glb');
  const {actions}= useAnimations(animations, group);
  useEffect(() => {
    if(animations.length >0){
        actions[animations[0].name]?.play();
    }
  }, [actions, animations]);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.material_0}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/models/bob_ross_painting.glb')
